APPLICATIONS = [
    {
        "application_id": "app-001",
        "application_name": "YouTube",
        "category": "Video Streaming",
        "traffic_profile": "video_streaming",
        "latency_sensitivity": "medium",
        "packet_loss_sensitivity": "medium",
    },
    {
        "application_id": "app-002",
        "application_name": "Netflix",
        "category": "Video Streaming",
        "traffic_profile": "video_streaming",
        "latency_sensitivity": "low",
        "packet_loss_sensitivity": "medium",
    },
    {
        "application_id": "app-003",
        "application_name": "TikTok",
        "category": "Social Media",
        "traffic_profile": "social_media",
        "latency_sensitivity": "low",
        "packet_loss_sensitivity": "low",
    },
    {
        "application_id": "app-004",
        "application_name": "WhatsApp",
        "category": "Messaging",
        "traffic_profile": "messaging",
        "latency_sensitivity": "medium",
        "packet_loss_sensitivity": "low",
    },
    {
        "application_id": "app-005",
        "application_name": "Instagram",
        "category": "Social Media",
        "traffic_profile": "social_media",
        "latency_sensitivity": "low",
        "packet_loss_sensitivity": "low",
    },
    {
        "application_id": "app-006",
        "application_name": "Spotify",
        "category": "Audio Streaming",
        "traffic_profile": "audio_streaming",
        "latency_sensitivity": "low",
        "packet_loss_sensitivity": "low",
    },
    {
        "application_id": "app-007",
        "application_name": "Zoom",
        "category": "Real-Time Communication",
        "traffic_profile": "real_time",
        "latency_sensitivity": "high",
        "packet_loss_sensitivity": "high",
    },
]